"""Add device_source to attendance_logs

Revision ID: 79b88f3f4979
Revises: d439c2c0d37a
Create Date: 2026-03-14 02:34:13.546505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b88f3f4979'
down_revision: Union[str, None] = 'd439c2c0d37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_logs', sa.Column('device_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_logs', 'device_source')
    # ### end Alembic commands ###
