"""add_names_to_student

Revision ID: d439c2c0d37a
Revises: cecff12a800e
Create Date: 2026-03-08 01:36:20.803172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd439c2c0d37a'
down_revision: Union[str, None] = 'cecff12a800e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('students', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_students_dni'), 'students', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_dni'), table_name='students')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
