"""add_module_permissions_table

Revision ID: ecfdf8217ba1
Revises: 93aa462961fe
Create Date: 2026-04-03 02:11:51.139284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfdf8217ba1'
down_revision: Union[str, None] = '93aa462961fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_permissions_id'), 'module_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_module_permissions_module_name'), 'module_permissions', ['module_name'], unique=False)
    op.create_index(op.f('ix_module_permissions_role'), 'module_permissions', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_permissions_role'), table_name='module_permissions')
    op.drop_index(op.f('ix_module_permissions_module_name'), table_name='module_permissions')
    op.drop_index(op.f('ix_module_permissions_id'), table_name='module_permissions')
    op.drop_table('module_permissions')
    # ### end Alembic commands ###
