from .student import Student
from .attendance import AttendanceLog
from .user import User
from .schedule import Schedule
from .justification import Justification
from .device import Device
from .telegram import TelegramConfig
from .assignment import Assignment
from .announcement import Announcement
from .module_permission import ModulePermission
